server:
  port: 8080
  
spring:
  application:
    name: api-gateway
    
eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
      
zuul:
  host:
    time-to-live: -1
    connect-timeout-millis: 5000
    socket-timeout-millis: 60000
    max-per-route-connections: 10000
    max-total-connections: 5000
  semaphore:
    max-semaphores: 500
  ignored-services: '*'
  sensitive-headers: Cookie,Set-Cookie
  routes:
    oauth:
      path: /oauth/**
      service-id: customer-service
      strip-prefix: false
    customer-service:
      path: /customer/**
      service-id: customer-service
      strip-prefix: true
    reservation-service:
      path: /reservation/**
      service-id: reservation-service
      strip-prefix: true
    payment-service:
      path: /payment/**
      service-id: payment-service
      strip-prefix: true
    hotel-management-service:
      path: /hotel-management/**
      service-id: hotel-management-service
      strip-prefix: true
    notification-service:
      path: /notification/**
      service-id: notification-service
      strip-prefix: true

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 122000
ribbon:
  ReadTimeout: 60000
  connection-timeout: 3000
  eureka:
    enabled: true
      
security:
  oauth2:
    resource:
      jwt:
        key-value: 123